# Generated by Django 5.0.1 on 2024-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_comment_booking_email_booking_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='john.smith@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='69...', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='surname',
            field=models.CharField(default='Smith', max_length=255),
        ),
    ]
