# Generated by Django 5.0.2 on 2024-02-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_haircut_category_alter_haircut_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircut',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
