# Generated by Django 5.0.2 on 2024-02-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_haircut_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircut',
            name='image',
            field=models.ImageField(blank=True, default='http://localhost:8000/media/haircuts/sample.jpg', null=True, upload_to='haircuts/'),
        ),
    ]
