# Generated by Django 5.0.2 on 2024-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_haircut_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='barbers/sample.jpg', null=True, upload_to='barbers/'),
        ),
    ]
