# Generated by Django 5.0.2 on 2024-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircut',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
